name: .NET

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      event_name: ${{ github.event_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x       
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x       
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x       
    - name: Setup Gitversion
      run: |
        dotnet tool install -g PowerShell
        dotnet tool install -g gitversion.tool
        dotnet-gitversion
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      if: ${{ github.event_name != 'release' }}
      run: dotnet build -c Debug --no-restore 
    - name: Build Release
      if: ${{ github.event_name == 'release' }}
      run: dotnet build -c Release --no-restore 
    - name: Tests
      run: dotnet test --no-build
    - name: Publish
      if: ${{ github.event_name == 'release' }}
      run: | 
        pwsh -c "{
          $packages - gci *.symbols.nupkg -Directory src\** -ErrorAction Stop
          $packages.FullName
          $packages.FullName | forEach-Object -process {
            dotnet nuget push $_ -k "${{ secrets.NUGET_KEY }}" -s https://api.nuget.org/v3/index.json --skip-duplicate
          }"
